# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_PDSMw7E4nMhGKLsy9kKswwHQjbXS2p3
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# 1. Load Data
ticker = "AAPL"
df = yf.download(ticker, start="2020-01-01", end="2024-01-01")
df.columns = df.columns.get_level_values(0)

# yf.download returns a multi-index dataframe in newer versions, we flatten it for simplicity if needed,
# but usually it's fine for single tickers.

print(df.head())
print("\n")

# 2. Feature Engineering
df['MA_10'] = df['Close'].rolling(10).mean()
df['MA_20'] = df['Close'].rolling(20).mean()
df['Return_Tomorrow'] = df['Close'].pct_change().shift(-1)  # target: tomorrow's % change
df.dropna(inplace=True)

# 3. Features & Target
features = ['Open', 'High', 'Low', 'Close', 'Volume', 'MA_10', 'MA_20']
X = df[features]
y = df['Return_Tomorrow']

# 4. Train/Test Split
split_idx = int(len(df) * 0.8)
X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

# 5. Train Model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 6. Predict & Convert Back to Price
predictions = model.predict(X_test)
last_prices = df['Close'].iloc[split_idx:].values
predicted_prices = last_prices * (1 + predictions)
actual_prices = last_prices * (1 + y_test.values)

rmse = np.sqrt(mean_squared_error(actual_prices, predicted_prices))
print(f"Root Mean Squared Error: ${rmse:.2f}")
print("\n")

# 7. Plot
plt.figure(figsize=(12, 6))
plt.plot(y_test.index, actual_prices, label='Actual Next Close')
plt.plot(y_test.index, predicted_prices, label='Predicted Next Close', alpha=0.7)
plt.title(f"{ticker} Stock Price Prediction (Test Set)")
plt.legend()
plt.show()